# Form implementation generated from reading ui file 'd:\Files\Desktop\chapter5\ui\Displayer2D.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from widget.GraphicsView import GraphicsScene, GraphicsView


class Ui_Displayer2D(object):
    def setupUi(self, Displayer2D):
        Displayer2D.setObjectName("Displayer2D")
        Displayer2D.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Displayer2D.sizePolicy().hasHeightForWidth())
        Displayer2D.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Displayer2D)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        scene = GraphicsScene()
        self.imageDisplay = GraphicsView(scene, Displayer2D)
        self.imageDisplay.setObjectName("imageDisplay")
        self.horizontalLayout1.addWidget(self.imageDisplay)
        self.imageScroll = QtWidgets.QScrollBar(parent=Displayer2D)
        self.imageScroll.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.imageScroll.setObjectName("imageScroll")
        self.horizontalLayout1.addWidget(self.imageScroll)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view = QtWidgets.QLabel(parent=Displayer2D)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view.setFont(font)
        self.view.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.view.setObjectName("view")
        self.horizontalLayout.addWidget(self.view)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.fitButton = QtWidgets.QPushButton(parent=Displayer2D)
        self.fitButton.setCheckable(False)
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout.addWidget(self.fitButton)
        self.sliceCurrent = QtWidgets.QLabel(parent=Displayer2D)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceCurrent.setFont(font)
        self.sliceCurrent.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sliceCurrent.setObjectName("sliceCurrent")
        self.horizontalLayout.addWidget(self.sliceCurrent)
        self.sliceChar = QtWidgets.QLabel(parent=Displayer2D)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceChar.setFont(font)
        self.sliceChar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sliceChar.setObjectName("sliceChar")
        self.horizontalLayout.addWidget(self.sliceChar)
        self.sliceTotal = QtWidgets.QLabel(parent=Displayer2D)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceTotal.setFont(font)
        self.sliceTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sliceTotal.setObjectName("sliceTotal")
        self.horizontalLayout.addWidget(self.sliceTotal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Displayer2D)
        QtCore.QMetaObject.connectSlotsByName(Displayer2D)

    def retranslateUi(self, Displayer2D):
        _translate = QtCore.QCoreApplication.translate
        Displayer2D.setWindowTitle(_translate("Displayer2D", "displayWindow"))
        self.view.setText(_translate("Displayer2D", "视图"))
        self.fitButton.setText(_translate("Displayer2D", "自适应"))
        self.sliceCurrent.setText(_translate("Displayer2D", "0"))
        self.sliceChar.setText(_translate("Displayer2D", "/"))
        self.sliceTotal.setText(_translate("Displayer2D", "0"))
