# Form implementation generated from reading ui file 'd:\Files\Desktop\chapter5\ui\Displayer2D.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Displayer2D(object):
    def setupUi(self, Displayer2D):
        Displayer2D.setObjectName("Displayer2D")
        Displayer2D.resize(800, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Displayer2D)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageDisplay = QtWidgets.QGraphicsView(parent=Displayer2D)
        self.imageDisplay.setObjectName("imageDisplay")
        self.verticalLayout.addWidget(self.imageDisplay)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewInformation = QtWidgets.QLabel(parent=Displayer2D)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewInformation.setFont(font)
        self.viewInformation.setObjectName("viewInformation")
        self.horizontalLayout.addWidget(self.viewInformation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.zoomBtn = QtWidgets.QPushButton(parent=Displayer2D)
        self.zoomBtn.setObjectName("zoomBtn")
        self.horizontalLayout.addWidget(self.zoomBtn)
        self.sliceInformation = QtWidgets.QLabel(parent=Displayer2D)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceInformation.setFont(font)
        self.sliceInformation.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sliceInformation.setObjectName("sliceInformation")
        self.horizontalLayout.addWidget(self.sliceInformation)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Displayer2D)
        QtCore.QMetaObject.connectSlotsByName(Displayer2D)

    def retranslateUi(self, Displayer2D):
        _translate = QtCore.QCoreApplication.translate
        Displayer2D.setWindowTitle(_translate("Displayer2D", "displayWindow"))
        self.viewInformation.setText(_translate("Displayer2D", "横断面"))
        self.zoomBtn.setText(_translate("Displayer2D", "缩放"))
        self.sliceInformation.setText(_translate("Displayer2D", "1/100"))
